version: '2.1'
executors:
  php8-1:
    docker:
      - image: php:8.1-alpine
    working_directory: ~/repo
  php8-2:
    docker:
      - image: php:8.2-alpine
    working_directory: ~/repo

jobs:
  # In the minimum PHP version supported, run all our quality checks.
  composer8-1:
    executor: php8-1
    steps:
      - run:
          name: Install alpine requirements for checkout
          command: apk add git openssh-client curl
      - checkout
      - restore_cache:
          key: composer-{{ checksum "composer.json" }}-{{ checksum "composer.lock" }}
      - run:
          name: composer
          command: |
            if [[ ! -f vendor/autoload.php ]]; then
                curl https://getcomposer.org/composer-stable.phar --location --silent  --output /usr/bin/composer; \
                chmod +x /usr/bin/composer; \
                composer install --no-progress --no-interaction; \
            fi
      - save_cache:
          key: composer-{{ checksum "composer.json" }}-{{ checksum "composer.lock" }}
          paths:
            - ./vendor
      - persist_to_workspace:
          root: .
          paths:
            - vendor

  phpcsfixer8-1:
    executor: php8-1
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: phpcs
          command: vendor/bin/php-cs-fixer fix -v --dry-run --allow-risky=yes

  phpcs8-1:
    executor: php8-1
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: phpcs
          command: vendor/bin/phpcs -n

  phpstan8-1:
    executor: php8-1
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: phpstan
          command: vendor/bin/phpstan analyse --memory-limit=256M

  phpunit8-1:
    executor: php8-1
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: phpunit
          command: vendor/bin/phpunit --testdox

  # In higher versions of PHP, run only PHPUnit.
  composer8-2:
    executor: php8-2
    steps:
      - run:
          name: Install alpine requirements for checkout
          command: apk add git openssh-client curl
      - checkout
      - restore_cache:
          key: composer-{{ checksum "composer.json" }}-{{ checksum "composer.lock" }}
      - run:
          name: composer
          command: |
            if [[ ! -f vendor/autoload.php ]]; then
                curl https://getcomposer.org/composer-stable.phar --location --silent  --output /usr/bin/composer; \
                chmod +x /usr/bin/composer; \
                composer install --no-progress --no-interaction; \
            fi
      - save_cache:
          key: composer-{{ checksum "composer.json" }}-{{ checksum "composer.lock" }}
          paths:
            - ./vendor
      - persist_to_workspace:
          root: .
          paths:
            - vendor

  phpunit8-2:
    executor: php8-2
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: phpunit
          command: vendor/bin/phpunit --testdox

workflows:
  version: '2.1'
  Code quality:
    jobs:
      - composer8-1
      - composer8-2
      - phpcs8-1:
          requires:
            - composer8-1
      - phpcsfixer8-1:
          requires:
            - composer8-1
      - phpstan8-1:
          requires:
            - composer8-1
      - phpunit8-1:
          requires:
            - composer8-1
      - phpunit8-2:
          requires:
            - composer8-2
